import type { Locale } from '@/i18n/locales'

/* Interface strings. uz is the base; every key must exist in uz. Builders add keys here as they need them. */
const uz = {
  'site.name': 'HEAD skills',
  'meta.description': 'Claude Code, Codex, Cursor va boshqa agentlar uchun HEAD skillʼlari. Bitta buyruq bilan oʻrnating.',
  'nav.marketplace': 'Marketplace',
  'nav.submit': 'Skill yuborish',
  'nav.headuz': 'head.uz',
  'hero.title': 'Agentingizni kuchaytiring',
  'hero.sub': 'Claude Code, Codex va Cursor uchun HEAD skillʼlari',
  'search.placeholder': 'Skill qidirish',
  'tab.all': 'Hammasi',
  'tab.skills': 'Skillʼlar',
  'tab.bundles': 'Toʻplamlar',
  'empty.title': 'Hech narsa topilmadi',
  'empty.sub': 'Boshqa soʻz bilan qidirib koʻring',
  'footer.replay': 'Introni qayta koʻrish',
  /* shell */
  'nav.menu': 'Menyu',
  'nav.guide': 'Qoʻllanma',
  'nav.language': 'Til',
  'search.clear': 'Tozalash',
  'search.results': '“{q}” boʻyicha natijalar',
  'section.viewAll': 'Barchasini koʻrish',
  'filter.category': 'Kategoriya',
  'filter.source': 'Manba',
  'filter.allCategories': 'Barcha kategoriyalar',
  'filter.reset': 'Filtrlarni tozalash',
  'source.head': 'HEAD jamoasi',
  'source.praktikum': 'AI Praktikum',
  'source.community': 'Hamjamiyat',
  'sort.featured': 'Tanlangan',
  'sort.latest': 'Yangi',
  'list.featured': 'Tanlanganlar',
  'card.by': 'Muallif: {name}',
  'card.skillsN': '{n} ta skill',
  'card.updated': 'Yangilangan: {date}',
  'card.copy': 'Oʻrnatish buyrugʻini nusxalash',
  'card.copied': 'Nusxalandi',
  'card.install': 'Oʻrnatish',
  'side.ctaTitle': 'Sizda skill bormi?',
  'side.ctaText': 'Uni HEAD hamjamiyati bilan ulashing.',
  'cta.title': 'Tajribangizni agent imkoniyatiga aylantiring',
  'cta.sub': 'Skill yarating, ulashing va boshqalarga yordam bering',
  'footer.tagline': 'Agentingiz uchun\nskillʼlar.',
  'footer.colMarket': 'Marketplace',
  'footer.colHead': 'HEAD',
  'footer.colLang': 'Til',
  'footer.consulting': 'Konsalting',
  'footer.team': 'Jamoa',
  'footer.github': 'GitHub',
  'footer.top': 'Yuqoriga',
  'footer.rights': '© {year} HEAD, Toshkent',
  'notfound.title': 'Sahifa topilmadi',
  'notfound.sub': 'Bu manzilda hech narsa yoʻq. Balki skill koʻchirilgan yoki havola xato yozilgan.',
  'notfound.back': 'Marketplaceʼga qaytish',
  /* end shell */
  /* detail pages (skill / bundle / submit) */
  'crumb.market': 'Marketplace',
  'crumb.submit': 'Skill yuborish',
  'meta.updated': 'Yangilangan: {date}',
  'meta.by': 'Muallif: {name}',
  'meta.skills': '{n} ta skill',
  'act.share': 'Ulashish',
  'act.copyLink': 'Havolani nusxalash',
  'act.linkCopied': 'Nusxalandi',
  'act.download': 'Yuklab olish',
  'act.github': 'GitHub',
  'tab.guides': 'Qoʻllanma',
  'tab.files': 'Fayllar',
  'install.title': 'Oʻrnatish',
  'install.sub': 'Agentga topshiring yoki oʻzingiz oʻrnating',
  'install.subBundle': 'Barcha skillʼlar bitta buyruq bilan',
  'install.agent': 'Agent uchun',
  'install.agentHint': 'Bu matnni Claude Code, Codex, Cursor yoki boshqa agentga yuboring - qolganini u bajaradi.',
  'install.human': 'Inson uchun',
  'install.step1': 'Node.js oʻrnating (LTS versiyasi).',
  'install.step1Link': 'nodejs.org',
  'install.step2': 'Terminalni oching va buyruqni ishga tushiring:',
  'install.step3': 'Claude.ai yoki Claude desktop uchun: ZIP faylni yuklab oling va Settings → Capabilities → Skills boʻlimiga yuklang.',
  'install.step3Zip': '{name}.zip',
  'install.step3Many': 'Claude.ai yoki Claude desktop uchun: har bir skillʼning ZIP faylini yuklab oling va Settings → Capabilities → Skills boʻlimiga yuklang.',
  'install.step4': 'Agentni qayta ishga tushiring va skill roʻyxatda paydo boʻlganini tekshiring.',
  'install.more': 'Hammasini koʻrish',
  'install.less': 'Yigʻish',
  'install.plugin': 'Claude Code plagini',
  'copy.copy': 'Nusxalash',
  'copy.copied': 'Nusxalandi',
  'copy.agent': 'Agent uchun koʻrsatmani nusxalash',
  'copy.steps': 'Barcha qadamlarni nusxalash',
  'copy.command': 'Buyruqni nusxalash',
  'copy.file': 'Faylni nusxalash',
  'dl.zip': 'ZIP yuklab olish',
  'video.title': 'Video tushuntirish',
  'video.play': 'Videoni ijro etish: {title}',
  'fm.name': 'Nomi',
  'fm.version': 'Versiya',
  'fm.description': 'Tavsif',
  'fm.category': 'Kategoriya',
  'fm.author': 'Muallif',
  'fm.license': 'Litsenziya',
  'fm.folder': 'Papka',
  'files.label': 'Fayllar',
  'files.noPreview': 'Bu fayl uchun koʻrinish mavjud emas',
  'files.noPreviewSub': 'Faylni koʻrish uchun ZIP arxivni yuklab oling.',
  'files.lines': '{n} qator',
  'bundle.kind': 'Toʻplam',
  'bundle.included': 'Toʻplamdagi skillʼlar',
  'bundle.open': 'Ochish',
  'badge.official': 'HEAD',
  'badge.praktikum-2026': 'Praktikum',
  'nf.skill': 'Bunday skill topilmadi',
  'nf.bundle': 'Bunday toʻplam topilmadi',
  'nf.sub': 'Havola eskirgan boʻlishi mumkin. Marketplaceʼdan qidirib koʻring.',
  'nf.back': 'Marketplaceʼga qaytish',
  'submit.title': 'Skill yuborish',
  'submit.lead': 'AI Praktikum talabalari va hamjamiyat uchun: oʻz skillʼingizni HEAD skillsʼga qanday qoʻshish boʻyicha qoʻllanma.',
  'submit.cardTitle': 'Pull request oching',
  'submit.cardSub': 'Skillʼlar GitHub orqali qabul qilinadi',
  'submit.repo': 'Repozitoriy',
  'submit.openRepo': 'GitHubʼda ochish',
  'submit.template': 'Papka shabloni',
  'submit.checks': 'Avtomatik tekshiruvlar',
  'submit.review': 'Har bir PRʼni maintainer koʻrib chiqadi.',
  'fm.more': 'Batafsil',
  'fm.less': 'Yigʻish',
  'submit.local': 'Oʻzingizda tekshiring',
  'install.plainZip': 'ZIP:',
  /* end detail */
} as const

export type ChromeKey = keyof typeof uz
type Dict = Record<ChromeKey, string>

const ru: Dict = {
  'site.name': 'HEAD skills',
  'meta.description': 'Скиллы HEAD для Claude Code, Codex, Cursor и других агентов. Устанавливаются одной командой.',
  'nav.marketplace': 'Маркетплейс',
  'nav.submit': 'Добавить скилл',
  'nav.headuz': 'head.uz',
  'hero.title': 'Прокачайте своего агента',
  'hero.sub': 'Скиллы HEAD для Claude Code, Codex и Cursor',
  'search.placeholder': 'Поиск скиллов',
  'tab.all': 'Все',
  'tab.skills': 'Скиллы',
  'tab.bundles': 'Наборы',
  'empty.title': 'Ничего не найдено',
  'empty.sub': 'Попробуйте другое слово',
  'footer.replay': 'Посмотреть интро снова',
  /* shell */
  'nav.menu': 'Меню',
  'nav.guide': 'Руководство',
  'nav.language': 'Язык',
  'search.clear': 'Очистить',
  'search.results': 'Результаты по «{q}»',
  'section.viewAll': 'Смотреть все',
  'filter.category': 'Категория',
  'filter.source': 'Источник',
  'filter.allCategories': 'Все категории',
  'filter.reset': 'Сбросить фильтры',
  'source.head': 'Команда HEAD',
  'source.praktikum': 'AI Praktikum',
  'source.community': 'Сообщество',
  'sort.featured': 'Избранные',
  'sort.latest': 'Новые',
  'list.featured': 'Избранное',
  'card.by': 'Автор: {name}',
  'card.skillsN': 'Скиллов: {n}',
  'card.updated': 'Обновлено: {date}',
  'card.copy': 'Скопировать команду установки',
  'card.copied': 'Скопировано',
  'card.install': 'Установить',
  'side.ctaTitle': 'Есть свой скилл?',
  'side.ctaText': 'Поделитесь им с сообществом HEAD.',
  'cta.title': 'Превратите свой опыт в навыки агентов',
  'cta.sub': 'Создавайте, делитесь и помогайте другим',
  'footer.tagline': 'Скиллы\nдля ваших агентов.',
  'footer.colMarket': 'Маркетплейс',
  'footer.colHead': 'HEAD',
  'footer.colLang': 'Язык',
  'footer.consulting': 'Консалтинг',
  'footer.team': 'Команда',
  'footer.github': 'GitHub',
  'footer.top': 'Наверх',
  'footer.rights': '© {year} HEAD, Ташкент',
  'notfound.title': 'Страница не найдена',
  'notfound.sub': 'По этому адресу ничего нет. Возможно, скилл переехал или в ссылке опечатка.',
  'notfound.back': 'Вернуться в маркетплейс',
  /* end shell */
  /* detail pages (skill / bundle / submit) */
  'crumb.market': 'Маркетплейс',
  'crumb.submit': 'Добавить скилл',
  'meta.updated': 'Обновлено {date}',
  'meta.by': 'Автор: {name}',
  'meta.skills': 'Скиллов: {n}',
  'act.share': 'Поделиться',
  'act.copyLink': 'Скопировать ссылку',
  'act.linkCopied': 'Скопировано',
  'act.download': 'Скачать',
  'act.github': 'GitHub',
  'tab.guides': 'Описание',
  'tab.files': 'Файлы',
  'install.title': 'Установка',
  'install.sub': 'Через агента или вручную',
  'install.subBundle': 'Все скиллы одной командой',
  'install.agent': 'Для агента',
  'install.agentHint': 'Отправьте этот текст в Claude Code, Codex, Cursor или другой агент — остальное он сделает сам.',
  'install.human': 'Для человека',
  'install.step1': 'Установите Node.js (версию LTS).',
  'install.step1Link': 'nodejs.org',
  'install.step2': 'Откройте терминал и выполните команду:',
  'install.step3': 'Для Claude.ai или Claude desktop: скачайте ZIP и загрузите его в Settings → Capabilities → Skills.',
  'install.step3Zip': '{name}.zip',
  'install.step3Many': 'Для Claude.ai или Claude desktop: скачайте ZIP каждого скилла и загрузите в Settings → Capabilities → Skills.',
  'install.step4': 'Перезапустите агента и проверьте, что скилл появился в списке.',
  'install.more': 'Показать всё',
  'install.less': 'Свернуть',
  'install.plugin': 'Плагин Claude Code',
  'copy.copy': 'Копировать',
  'copy.copied': 'Скопировано',
  'copy.agent': 'Скопировать инструкцию для агента',
  'copy.steps': 'Скопировать все шаги',
  'copy.command': 'Скопировать команду',
  'copy.file': 'Скопировать файл',
  'dl.zip': 'Скачать ZIP',
  'video.title': 'Видео-объяснение',
  'video.play': 'Смотреть видео: {title}',
  'fm.name': 'Имя',
  'fm.version': 'Версия',
  'fm.description': 'Описание',
  'fm.category': 'Категория',
  'fm.author': 'Автор',
  'fm.license': 'Лицензия',
  'fm.folder': 'Папка',
  'files.label': 'Файлы',
  'files.noPreview': 'Предпросмотр недоступен',
  'files.noPreviewSub': 'Скачайте ZIP-архив, чтобы открыть этот файл.',
  'files.lines': 'Строк: {n}',
  'bundle.kind': 'Набор',
  'bundle.included': 'Скиллы в наборе',
  'bundle.open': 'Открыть',
  'badge.official': 'HEAD',
  'badge.praktikum-2026': 'Praktikum',
  'nf.skill': 'Скилл не найден',
  'nf.bundle': 'Набор не найден',
  'nf.sub': 'Возможно, ссылка устарела. Попробуйте поиск в маркетплейсе.',
  'nf.back': 'Вернуться в маркетплейс',
  'submit.title': 'Добавить скилл',
  'submit.lead': 'Для студентов AI Praktikum и сообщества: как добавить свой скилл в HEAD skills.',
  'submit.cardTitle': 'Откройте pull request',
  'submit.cardSub': 'Скиллы принимаются через GitHub',
  'submit.repo': 'Репозиторий',
  'submit.openRepo': 'Открыть на GitHub',
  'submit.template': 'Шаблон папки',
  'submit.checks': 'Автоматические проверки',
  'submit.review': 'Каждый PR проверяет мейнтейнер.',
  'fm.more': 'Показать полностью',
  'fm.less': 'Свернуть',
  'submit.local': 'Проверьте у себя',
  'install.plainZip': 'ZIP:',
  /* end detail */
}

const en: Dict = {
  'site.name': 'HEAD skills',
  'meta.description': 'HEAD skills for Claude Code, Codex, Cursor and other agents. Install with one command.',
  'nav.marketplace': 'Marketplace',
  'nav.submit': 'Submit a skill',
  'nav.headuz': 'head.uz',
  'hero.title': 'Supercharge your AI agents',
  'hero.sub': 'HEAD skills for Claude Code, Codex, Cursor and more',
  'search.placeholder': 'Search skills',
  'tab.all': 'All',
  'tab.skills': 'Skills',
  'tab.bundles': 'Bundles',
  'empty.title': 'No matching results found',
  'empty.sub': 'Try a different keyword',
  'footer.replay': 'Replay the intro',
  /* shell */
  'nav.menu': 'Menu',
  'nav.guide': 'Guide',
  'nav.language': 'Language',
  'search.clear': 'Clear',
  'search.results': 'Results for “{q}”',
  'section.viewAll': 'View all',
  'filter.category': 'Category',
  'filter.source': 'Source',
  'filter.allCategories': 'All categories',
  'filter.reset': 'Clear filters',
  'source.head': 'HEAD team',
  'source.praktikum': 'AI Praktikum',
  'source.community': 'Community',
  'sort.featured': 'Featured',
  'sort.latest': 'Latest',
  'list.featured': 'Featured',
  'card.by': 'By {name}',
  'card.skillsN': '{n} skills',
  'card.updated': 'Updated {date}',
  'card.copy': 'Copy install command',
  'card.copied': 'Copied',
  'card.install': 'Install',
  'side.ctaTitle': 'Have a skill?',
  'side.ctaText': 'Share it with the HEAD community.',
  'cta.title': 'Turn your expertise into agent skills',
  'cta.sub': 'Create, share and help others',
  'footer.tagline': 'Skills for\nyour agents.',
  'footer.colMarket': 'Marketplace',
  'footer.colHead': 'HEAD',
  'footer.colLang': 'Language',
  'footer.consulting': 'Consulting',
  'footer.team': 'Team',
  'footer.github': 'GitHub',
  'footer.top': 'Back to top',
  'footer.rights': '© {year} HEAD, Tashkent',
  'notfound.title': 'Page not found',
  'notfound.sub': 'Nothing lives at this address. The skill may have moved, or the link has a typo.',
  'notfound.back': 'Back to the marketplace',
  /* end shell */
  /* detail pages (skill / bundle / submit) */
  'crumb.market': 'Marketplace',
  'crumb.submit': 'Submit a skill',
  'meta.updated': 'Updated {date}',
  'meta.by': 'By {name}',
  'meta.skills': '{n} skills',
  'act.share': 'Share',
  'act.copyLink': 'Copy link',
  'act.linkCopied': 'Copied',
  'act.download': 'Download',
  'act.github': 'GitHub',
  'tab.guides': 'Guides',
  'tab.files': 'Files',
  'install.title': 'Install',
  'install.sub': 'Hand it to your agent or do it yourself',
  'install.subBundle': 'Every skill, one command',
  'install.agent': 'For Agent',
  'install.agentHint': 'Paste this into Claude Code, Codex, Cursor or any agent — it does the rest.',
  'install.human': 'For Human',
  'install.step1': 'Install Node.js (the LTS version).',
  'install.step1Link': 'nodejs.org',
  'install.step2': 'Open a terminal and run:',
  'install.step3': 'For Claude.ai or Claude desktop: download the ZIP and upload it under Settings → Capabilities → Skills.',
  'install.step3Zip': '{name}.zip',
  'install.step3Many': 'For Claude.ai or Claude desktop: download each skill’s ZIP and upload it under Settings → Capabilities → Skills.',
  'install.step4': 'Restart your agent and check the skill shows up.',
  'install.more': 'Show all',
  'install.less': 'Show less',
  'install.plugin': 'Claude Code plugin',
  'copy.copy': 'Copy',
  'copy.copied': 'Copied',
  'copy.agent': 'Copy the agent prompt',
  'copy.steps': 'Copy all steps',
  'copy.command': 'Copy command',
  'copy.file': 'Copy file',
  'dl.zip': 'Download ZIP',
  'video.title': 'Video explainer',
  'video.play': 'Play video: {title}',
  'fm.name': 'Name',
  'fm.version': 'Version',
  'fm.description': 'Description',
  'fm.category': 'Category',
  'fm.author': 'Author',
  'fm.license': 'License',
  'fm.folder': 'Folder',
  'files.label': 'Files',
  'files.noPreview': 'Preview not supported',
  'files.noPreviewSub': 'Download the ZIP to open this file.',
  'files.lines': '{n} lines',
  'bundle.kind': 'Bundle',
  'bundle.included': 'Skills in this bundle',
  'bundle.open': 'Open',
  'badge.official': 'HEAD',
  'badge.praktikum-2026': 'Praktikum',
  'nf.skill': 'Skill not found',
  'nf.bundle': 'Bundle not found',
  'nf.sub': 'The link may be out of date. Try searching the marketplace.',
  'nf.back': 'Back to the marketplace',
  'submit.title': 'Submit a skill',
  'submit.lead': 'For AI Praktikum students and the community: how to add your own skill to HEAD skills.',
  'submit.cardTitle': 'Open a pull request',
  'submit.cardSub': 'Skills are accepted through GitHub',
  'submit.repo': 'Repository',
  'submit.openRepo': 'Open on GitHub',
  'submit.template': 'Folder template',
  'submit.checks': 'Automated checks',
  'submit.review': 'A maintainer reviews every PR.',
  'fm.more': 'Show more',
  'fm.less': 'Show less',
  'submit.local': 'Check it locally',
  'install.plainZip': 'ZIP:',
  /* end detail */
}

export const chrome: Record<Locale, Dict> = { uz, ru, en }
