import type { Locale } from '@/i18n/locales'

/* Interface strings. uz is the base; every key must exist in uz. Builders add keys here as they need them. */
const uz = {
  'site.name': 'HEAD skills',
  'nav.marketplace': 'Marketplace',
  'nav.submit': 'Skill yuborish',
  'nav.headuz': 'head.uz',
  'hero.title': 'Agentingizni kuchaytiring',
  'hero.sub': 'Claude Code, Codex va Cursor uchun HEAD skill’lari',
  'search.placeholder': 'Skill qidirish',
  'tab.all': 'Hammasi',
  'tab.skills': 'Skill’lar',
  'tab.bundles': 'To‘plamlar',
  'empty.title': 'Hech narsa topilmadi',
  'empty.sub': 'Boshqa so‘z bilan qidirib ko‘ring',
  'footer.replay': 'Introni qayta ko‘rish',
  /* shell */
  'nav.menu': 'Menyu',
  'nav.language': 'Til',
  'search.clear': 'Tozalash',
  'search.results': '“{q}” bo‘yicha natijalar',
  'section.viewAll': 'Barchasini ko‘rish',
  'filter.category': 'Kategoriya',
  'filter.source': 'Manba',
  'filter.allCategories': 'Barcha kategoriyalar',
  'filter.reset': 'Filtrlarni tozalash',
  'source.head': 'HEAD jamoasi',
  'source.praktikum': 'AI Praktikum',
  'source.community': 'Hamjamiyat',
  'sort.featured': 'Tanlangan',
  'sort.latest': 'Yangi',
  'list.featured': 'Tanlanganlar',
  'card.by': 'Muallif: {name}',
  'card.skillsN': '{n} ta skill',
  'card.updated': 'Yangilangan: {date}',
  'card.copy': 'O‘rnatish buyrug‘ini nusxalash',
  'card.copied': 'Nusxalandi',
  'card.install': 'O‘rnatish',
  'side.ctaTitle': 'Sizda skill bormi?',
  'side.ctaText': 'Uni HEAD hamjamiyati bilan ulashing.',
  'cta.title': 'Tajribangizni agent imkoniyatiga aylantiring',
  'cta.sub': 'Skill yarating, ulashing va boshqalarga yordam bering',
  'footer.tagline': 'Agentingiz uchun\nskill’lar.',
  'footer.colMarket': 'Marketplace',
  'footer.colHead': 'HEAD',
  'footer.colLang': 'Til',
  'footer.consulting': 'Konsalting',
  'footer.team': 'Jamoa',
  'footer.github': 'GitHub',
  'footer.top': 'Yuqoriga',
  'footer.rights': '© {year} HEAD, Toshkent',
  'notfound.title': 'Sahifa topilmadi',
  'notfound.sub': 'Bu manzilda hech narsa yo‘q. Balki skill ko‘chirilgan yoki havola xato yozilgan.',
  'notfound.back': 'Marketplace’ga qaytish',
  /* end shell */
} as const

export type ChromeKey = keyof typeof uz
type Dict = Record<ChromeKey, string>

const ru: Dict = {
  'site.name': 'HEAD skills',
  'nav.marketplace': 'Маркетплейс',
  'nav.submit': 'Добавить скилл',
  'nav.headuz': 'head.uz',
  'hero.title': 'Прокачайте своего агента',
  'hero.sub': 'Скиллы HEAD для Claude Code, Codex и Cursor',
  'search.placeholder': 'Поиск скиллов',
  'tab.all': 'Все',
  'tab.skills': 'Скиллы',
  'tab.bundles': 'Наборы',
  'empty.title': 'Ничего не найдено',
  'empty.sub': 'Попробуйте другое слово',
  'footer.replay': 'Посмотреть интро снова',
  /* shell */
  'nav.menu': 'Меню',
  'nav.language': 'Язык',
  'search.clear': 'Очистить',
  'search.results': 'Результаты по «{q}»',
  'section.viewAll': 'Смотреть все',
  'filter.category': 'Категория',
  'filter.source': 'Источник',
  'filter.allCategories': 'Все категории',
  'filter.reset': 'Сбросить фильтры',
  'source.head': 'Команда HEAD',
  'source.praktikum': 'AI Praktikum',
  'source.community': 'Сообщество',
  'sort.featured': 'Избранные',
  'sort.latest': 'Новые',
  'list.featured': 'Избранное',
  'card.by': 'Автор: {name}',
  'card.skillsN': 'Скиллов: {n}',
  'card.updated': 'Обновлено: {date}',
  'card.copy': 'Скопировать команду установки',
  'card.copied': 'Скопировано',
  'card.install': 'Установить',
  'side.ctaTitle': 'Есть свой скилл?',
  'side.ctaText': 'Поделитесь им с сообществом HEAD.',
  'cta.title': 'Превратите свой опыт в навыки агентов',
  'cta.sub': 'Создавайте, делитесь и помогайте другим',
  'footer.tagline': 'Скиллы\nдля ваших агентов.',
  'footer.colMarket': 'Маркетплейс',
  'footer.colHead': 'HEAD',
  'footer.colLang': 'Язык',
  'footer.consulting': 'Консалтинг',
  'footer.team': 'Команда',
  'footer.github': 'GitHub',
  'footer.top': 'Наверх',
  'footer.rights': '© {year} HEAD, Ташкент',
  'notfound.title': 'Страница не найдена',
  'notfound.sub': 'По этому адресу ничего нет. Возможно, скилл переехал или в ссылке опечатка.',
  'notfound.back': 'Вернуться в маркетплейс',
  /* end shell */
}

const en: Dict = {
  'site.name': 'HEAD skills',
  'nav.marketplace': 'Marketplace',
  'nav.submit': 'Submit a skill',
  'nav.headuz': 'head.uz',
  'hero.title': 'Supercharge your AI agents',
  'hero.sub': 'HEAD skills for Claude Code, Codex, Cursor and more',
  'search.placeholder': 'Search skills',
  'tab.all': 'All',
  'tab.skills': 'Skills',
  'tab.bundles': 'Bundles',
  'empty.title': 'No matching results found',
  'empty.sub': 'Try a different keyword',
  'footer.replay': 'Replay the intro',
  /* shell */
  'nav.menu': 'Menu',
  'nav.language': 'Language',
  'search.clear': 'Clear',
  'search.results': 'Results for “{q}”',
  'section.viewAll': 'View all',
  'filter.category': 'Category',
  'filter.source': 'Source',
  'filter.allCategories': 'All categories',
  'filter.reset': 'Clear filters',
  'source.head': 'HEAD team',
  'source.praktikum': 'AI Praktikum',
  'source.community': 'Community',
  'sort.featured': 'Featured',
  'sort.latest': 'Latest',
  'list.featured': 'Featured',
  'card.by': 'By {name}',
  'card.skillsN': '{n} skills',
  'card.updated': 'Updated {date}',
  'card.copy': 'Copy install command',
  'card.copied': 'Copied',
  'card.install': 'Install',
  'side.ctaTitle': 'Have a skill?',
  'side.ctaText': 'Share it with the HEAD community.',
  'cta.title': 'Turn your expertise into agent skills',
  'cta.sub': 'Create, share and help others',
  'footer.tagline': 'Skills for\nyour agents.',
  'footer.colMarket': 'Marketplace',
  'footer.colHead': 'HEAD',
  'footer.colLang': 'Language',
  'footer.consulting': 'Consulting',
  'footer.team': 'Team',
  'footer.github': 'GitHub',
  'footer.top': 'Back to top',
  'footer.rights': '© {year} HEAD, Tashkent',
  'notfound.title': 'Page not found',
  'notfound.sub': 'Nothing lives at this address. The skill may have moved, or the link has a typo.',
  'notfound.back': 'Back to the marketplace',
  /* end shell */
}

export const chrome: Record<Locale, Dict> = { uz, ru, en }
