import { useLocale } from '@/i18n/useLocale'
import type { Locale } from '@/i18n/locales'

/* Detail / bundle / submit interface strings. Kept next to the components (not in content/chrome.ts) so the
   parallel builders never collide in one file; the lead can fold them into chrome.ts later. uz is the base. */
const uz = {
  'crumb.market': 'Marketplace',
  'crumb.submit': 'Skill yuborish',
  'meta.updated': 'Yangilangan: {date}',
  'meta.by': 'Muallif: {name}',
  'meta.skills': '{n} ta skill',
  'act.share': 'Ulashish',
  'act.copyLink': 'Havolani nusxalash',
  'act.linkCopied': 'Nusxalandi',
  'act.download': 'Yuklab olish',
  'act.github': 'GitHub',
  'tab.guides': 'Qoʻllanma',
  'tab.files': 'Fayllar',
  'tab.skills': 'Skillʼlar',
  'install.title': 'Oʻrnatish',
  'install.sub': 'Ikki yoʻl: agentga topshiring yoki oʻzingiz oʻrnating',
  'install.subBundle': 'Toʻplamdagi barcha skillʼlar bitta buyruq bilan oʻrnatiladi',
  'install.agent': 'Agent uchun',
  'install.agentHint': 'Bu matnni Claude Code, Codex, Cursor yoki boshqa agentga yuboring - qolganini u bajaradi.',
  'install.human': 'Inson uchun',
  'install.step1': 'Node.js oʻrnating (LTS versiyasi).',
  'install.step1Link': 'nodejs.org',
  'install.step2': 'Terminalni oching va buyruqni ishga tushiring:',
  'install.step3': 'Claude.ai yoki Claude desktop uchun: ZIP faylni yuklab oling va Settings → Capabilities → Skills boʻlimiga yuklang.',
  'install.step3Zip': '{name}.zip',
  'install.step3Many': 'Claude.ai yoki Claude desktop uchun: har bir skillʼning ZIP faylini yuklab oling va Settings → Capabilities → Skills boʻlimiga yuklang.',
  'install.step4': 'Agentni qayta ishga tushiring va skill roʻyxatda paydo boʻlganini tekshiring.',
  'install.plugin': 'Claude Code plagini',
  'copy.copy': 'Nusxalash',
  'copy.copied': 'Nusxalandi',
  'copy.agent': 'Agent uchun koʻrsatmani nusxalash',
  'copy.steps': 'Barcha qadamlarni nusxalash',
  'copy.command': 'Buyruqni nusxalash',
  'copy.file': 'Faylni nusxalash',
  'dl.zip': 'ZIP yuklab olish',
  'video.title': 'Video tushuntirish',
  'video.play': 'Videoni ijro etish: {title}',
  'fm.name': 'Nomi',
  'fm.version': 'Versiya',
  'fm.description': 'Tavsif',
  'fm.category': 'Kategoriya',
  'fm.author': 'Muallif',
  'fm.license': 'Litsenziya',
  'fm.folder': 'Papka',
  'files.label': 'Fayllar',
  'files.noPreview': 'Bu fayl uchun koʻrinish mavjud emas',
  'files.noPreviewSub': 'Faylni koʻrish uchun ZIP arxivni yuklab oling.',
  'files.lines': '{n} qator',
  'bundle.kind': 'Toʻplam',
  'bundle.included': 'Toʻplamdagi skillʼlar',
  'bundle.open': 'Ochish',
  'badge.official': 'HEAD',
  'badge.praktikum-2026': 'Praktikum 2026',
  'nf.skill': 'Bunday skill topilmadi',
  'nf.bundle': 'Bunday toʻplam topilmadi',
  'nf.sub': 'Havola eskirgan boʻlishi mumkin. Marketplaceʼdan qidirib koʻring.',
  'nf.back': 'Marketplaceʼga qaytish',
  'submit.title': 'Skill yuborish',
  'submit.lead': 'AI Praktikum talabalari va hamjamiyat uchun: oʻz skillʼingizni HEAD skillsʼga qanday qoʻshish boʻyicha qoʻllanma.',
  'submit.cardTitle': 'Pull request oching',
  'submit.cardSub': 'Skillʼlar GitHub orqali qabul qilinadi',
  'submit.repo': 'Repozitoriy',
  'submit.openRepo': 'GitHubʼda ochish',
  'submit.template': 'Papka shabloni',
  'submit.checks': 'Avtomatik tekshiruvlar',
  'submit.review': 'Har bir PRʼni maintainer koʻrib chiqadi.',
  'fm.more': 'Batafsil',
  'fm.less': 'Yigʻish',
  'submit.local': 'Oʻzingizda tekshiring',
  'install.plainZip': 'ZIP:',
}

export type DetailKey = keyof typeof uz
type Dict = Record<DetailKey, string>

const ru: Dict = {
  'crumb.market': 'Маркетплейс',
  'crumb.submit': 'Добавить скилл',
  'meta.updated': 'Обновлено {date}',
  'meta.by': 'Автор: {name}',
  'meta.skills': 'Скиллов: {n}',
  'act.share': 'Поделиться',
  'act.copyLink': 'Скопировать ссылку',
  'act.linkCopied': 'Скопировано',
  'act.download': 'Скачать',
  'act.github': 'GitHub',
  'tab.guides': 'Описание',
  'tab.files': 'Файлы',
  'tab.skills': 'Скиллы',
  'install.title': 'Установка',
  'install.sub': 'Два пути: поручите агенту или установите сами',
  'install.subBundle': 'Все скиллы набора ставятся одной командой',
  'install.agent': 'Для агента',
  'install.agentHint': 'Отправьте этот текст в Claude Code, Codex, Cursor или другой агент — остальное он сделает сам.',
  'install.human': 'Для человека',
  'install.step1': 'Установите Node.js (версию LTS).',
  'install.step1Link': 'nodejs.org',
  'install.step2': 'Откройте терминал и выполните команду:',
  'install.step3': 'Для Claude.ai или Claude desktop: скачайте ZIP и загрузите его в Settings → Capabilities → Skills.',
  'install.step3Zip': '{name}.zip',
  'install.step3Many': 'Для Claude.ai или Claude desktop: скачайте ZIP каждого скилла и загрузите в Settings → Capabilities → Skills.',
  'install.step4': 'Перезапустите агента и проверьте, что скилл появился в списке.',
  'install.plugin': 'Плагин Claude Code',
  'copy.copy': 'Копировать',
  'copy.copied': 'Скопировано',
  'copy.agent': 'Скопировать инструкцию для агента',
  'copy.steps': 'Скопировать все шаги',
  'copy.command': 'Скопировать команду',
  'copy.file': 'Скопировать файл',
  'dl.zip': 'Скачать ZIP',
  'video.title': 'Видео-объяснение',
  'video.play': 'Смотреть видео: {title}',
  'fm.name': 'Имя',
  'fm.version': 'Версия',
  'fm.description': 'Описание',
  'fm.category': 'Категория',
  'fm.author': 'Автор',
  'fm.license': 'Лицензия',
  'fm.folder': 'Папка',
  'files.label': 'Файлы',
  'files.noPreview': 'Предпросмотр недоступен',
  'files.noPreviewSub': 'Скачайте ZIP-архив, чтобы открыть этот файл.',
  'files.lines': 'Строк: {n}',
  'bundle.kind': 'Набор',
  'bundle.included': 'Скиллы в наборе',
  'bundle.open': 'Открыть',
  'badge.official': 'HEAD',
  'badge.praktikum-2026': 'Praktikum 2026',
  'nf.skill': 'Скилл не найден',
  'nf.bundle': 'Набор не найден',
  'nf.sub': 'Возможно, ссылка устарела. Попробуйте поиск в маркетплейсе.',
  'nf.back': 'Вернуться в маркетплейс',
  'submit.title': 'Добавить скилл',
  'submit.lead': 'Для студентов AI Praktikum и сообщества: как добавить свой скилл в HEAD skills.',
  'submit.cardTitle': 'Откройте pull request',
  'submit.cardSub': 'Скиллы принимаются через GitHub',
  'submit.repo': 'Репозиторий',
  'submit.openRepo': 'Открыть на GitHub',
  'submit.template': 'Шаблон папки',
  'submit.checks': 'Автоматические проверки',
  'submit.review': 'Каждый PR проверяет мейнтейнер.',
  'fm.more': 'Показать полностью',
  'fm.less': 'Свернуть',
  'submit.local': 'Проверьте у себя',
  'install.plainZip': 'ZIP:',
}

const en: Dict = {
  'crumb.market': 'Marketplace',
  'crumb.submit': 'Submit a skill',
  'meta.updated': 'Updated {date}',
  'meta.by': 'By {name}',
  'meta.skills': '{n} skills',
  'act.share': 'Share',
  'act.copyLink': 'Copy link',
  'act.linkCopied': 'Copied',
  'act.download': 'Download',
  'act.github': 'GitHub',
  'tab.guides': 'Guides',
  'tab.files': 'Files',
  'tab.skills': 'Skills',
  'install.title': 'Install',
  'install.sub': 'Two ways: hand it to your agent, or install it yourself',
  'install.subBundle': 'Every skill in the bundle, one command',
  'install.agent': 'For Agent',
  'install.agentHint': 'Paste this into Claude Code, Codex, Cursor or any agent — it does the rest.',
  'install.human': 'For Human',
  'install.step1': 'Install Node.js (the LTS version).',
  'install.step1Link': 'nodejs.org',
  'install.step2': 'Open a terminal and run:',
  'install.step3': 'For Claude.ai or Claude desktop: download the ZIP and upload it under Settings → Capabilities → Skills.',
  'install.step3Zip': '{name}.zip',
  'install.step3Many': 'For Claude.ai or Claude desktop: download each skill’s ZIP and upload it under Settings → Capabilities → Skills.',
  'install.step4': 'Restart your agent and check the skill shows up.',
  'install.plugin': 'Claude Code plugin',
  'copy.copy': 'Copy',
  'copy.copied': 'Copied',
  'copy.agent': 'Copy the agent prompt',
  'copy.steps': 'Copy all steps',
  'copy.command': 'Copy command',
  'copy.file': 'Copy file',
  'dl.zip': 'Download ZIP',
  'video.title': 'Video explainer',
  'video.play': 'Play video: {title}',
  'fm.name': 'Name',
  'fm.version': 'Version',
  'fm.description': 'Description',
  'fm.category': 'Category',
  'fm.author': 'Author',
  'fm.license': 'License',
  'fm.folder': 'Folder',
  'files.label': 'Files',
  'files.noPreview': 'Preview not supported',
  'files.noPreviewSub': 'Download the ZIP to open this file.',
  'files.lines': '{n} lines',
  'bundle.kind': 'Bundle',
  'bundle.included': 'Skills in this bundle',
  'bundle.open': 'Open',
  'badge.official': 'HEAD',
  'badge.praktikum-2026': 'Praktikum 2026',
  'nf.skill': 'Skill not found',
  'nf.bundle': 'Bundle not found',
  'nf.sub': 'The link may be out of date. Try searching the marketplace.',
  'nf.back': 'Back to the marketplace',
  'submit.title': 'Submit a skill',
  'submit.lead': 'For AI Praktikum students and the community: how to add your own skill to HEAD skills.',
  'submit.cardTitle': 'Open a pull request',
  'submit.cardSub': 'Skills are accepted through GitHub',
  'submit.repo': 'Repository',
  'submit.openRepo': 'Open on GitHub',
  'submit.template': 'Folder template',
  'submit.checks': 'Automated checks',
  'submit.review': 'A maintainer reviews every PR.',
  'fm.more': 'Show more',
  'fm.less': 'Show less',
  'submit.local': 'Check it locally',
  'install.plainZip': 'ZIP:',
}

const dicts: Record<Locale, Dict> = { uz, ru, en }

export function useDT() {
  const locale = useLocale()
  return (key: DetailKey, vars?: Record<string, string | number>): string => {
    let s: string = dicts[locale][key] ?? uz[key]
    if (vars) for (const [k, v] of Object.entries(vars)) s = s.replaceAll(`{${k}}`, String(v))
    return s
  }
}

export function formatDate(iso: string, locale: Locale): string {
  const d = new Date(iso)
  if (Number.isNaN(d.getTime())) return iso
  if (locale === 'uz') {
    // Intl's uz data is uneven across browsers; spell it out.
    const m = ['yanvar', 'fevral', 'mart', 'aprel', 'may', 'iyun', 'iyul', 'avgust', 'sentabr', 'oktabr', 'noyabr', 'dekabr']
    return `${d.getDate()}-${m[d.getMonth()]}, ${d.getFullYear()}`
  }
  return new Intl.DateTimeFormat(locale === 'ru' ? 'ru-RU' : 'en-US', { year: 'numeric', month: 'long', day: 'numeric' }).format(d)
}
